### ISSUE TITLE
As a restaurant owner, I want to see rests. in my area so that I can identify my competition and gather their info

### ISSUE THREAD

**Issue by berksonj** [nyu-software-engineering/spring-2020-idle-tower#17]
Time 6 hrs

- Display list of saved resturants 
- Each saved shows more info once clicked 
- List food check score, price, number of review 
- Displayed top-rated restaurants near your restaurant (by foodcheck score) 

Tasks:
#26, #27, #28, #29

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2020 - this, and most of your other user stories, are not written correctly.  Please review the concept of user stories.

**Comment by berksonj** [comment]
@bloombar , when we had our Sprint 0 stakeholder demo, Karan said this is the way we should do it

**Comment by bloombar** [comment]
@berksonj - ok, I will have to talk with Karan!  But please follow the standard format: https://knowledge.kitchen/Scrum_development_framework#User_stories
